sonar.projectKey=e-mart-eks-pipeline
sonar.projectName=e-mart-eks-pipeline
sonar.sources=client,nodeapi,javaapi
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/.metadata/**,**/coverage/**,**/target/**
